"""
Report Generator Module
"""
from typing import Dict, List
from pathlib import Path
import json
from datetime import datetime
from jinja2 import Template
from utils.logger import get_logger
from config import Config

logger = get_logger(__name__)


class ReportGenerator:
    """Generate reports in various formats"""
    
    HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Bug Bounty Report - {{ target }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; }
        .summary { background: #e9ecef; padding: 20px; border-radius: 5px; margin: 20px 0; }
        .severity-critical { color: #dc3545; font-weight: bold; }
        .severity-high { color: #fd7e14; font-weight: bold; }
        .severity-medium { color: #ffc107; font-weight: bold; }
        .severity-low { color: #28a745; }
        .severity-info { color: #17a2b8; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #007bff; color: white; }
        tr:hover { background-color: #f5f5f5; }
        .timestamp { color: #666; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔒 Bug Bounty Security Report</h1>
        <p class="timestamp">Generated: {{ timestamp }}</p>
        
        <div class="summary">
            <h2>📊 Executive Summary</h2>
            <p><strong>Target:</strong> {{ target }}</p>
            <p><strong>Scan Date:</strong> {{ scan_date }}</p>
            <p><strong>Total Findings:</strong> {{ total_findings }}</p>
            <ul>
                <li><span class="severity-critical">Critical:</span> {{ severity_counts.critical }}</li>
                <li><span class="severity-high">High:</span> {{ severity_counts.high }}</li>
                <li><span class="severity-medium">Medium:</span> {{ severity_counts.medium }}</li>
                <li><span class="severity-low">Low:</span> {{ severity_counts.low }}</li>
                <li><span class="severity-info">Info:</span> {{ severity_counts.info }}</li>
            </ul>
        </div>
        
        <h2>🔍 Reconnaissance Results</h2>
        <p><strong>Subdomains Found:</strong> {{ recon.subdomains }}</p>
        <p><strong>Open Ports:</strong> {{ recon.ports }}</p>
        <p><strong>Technologies Detected:</strong> {{ recon.technologies }}</p>
        <p><strong>URLs Discovered:</strong> {{ recon.urls }}</p>
        
        <h2>🚨 Vulnerabilities</h2>
        <table>
            <thead>
                <tr>
                    <th>Severity</th>
                    <th>Title</th>
                    <th>URL</th>
                    <th>Tool</th>
                </tr>
            </thead>
            <tbody>
                {% for vuln in vulnerabilities %}
                <tr>
                    <td class="severity-{{ vuln.severity }}">{{ vuln.severity|upper }}</td>
                    <td>{{ vuln.title }}</td>
                    <td>{{ vuln.url }}</td>
                    <td>{{ vuln.tool }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <h2>📝 Detailed Findings</h2>
        {% for vuln in vulnerabilities %}
        <div style="border-left: 4px solid {% if vuln.severity == 'critical' %}#dc3545{% elif vuln.severity == 'high' %}#fd7e14{% elif vuln.severity == 'medium' %}#ffc107{% else %}#28a745{% endif %}; padding-left: 15px; margin: 20px 0;">
            <h3>{{ vuln.title }}</h3>
            <p><strong>Severity:</strong> <span class="severity-{{ vuln.severity }}">{{ vuln.severity|upper }}</span></p>
            <p><strong>URL:</strong> {{ vuln.url }}</p>
            <p><strong>Description:</strong> {{ vuln.description }}</p>
            <p><strong>Tool:</strong> {{ vuln.tool }}</p>
        </div>
        {% endfor %}
        
        <footer style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; text-align: center;">
            <p>Generated by Bug Bounty Automation Tool</p>
        </footer>
    </div>
</body>
</html>
    """
    
    def __init__(self, target: str):
        self.target = target
        self.config = Config.get_reporting_config()
        self.output_dir = Path(self.config.get('output_dir', './reports'))
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate(self, format: str = 'html', output: str = None) -> str:
        """Generate report in specified format"""
        logger.info(f"Generating {format} report for {target}")
        
        # Gather data from database
        data = self._gather_data()
        
        if format == 'json':
            return self._generate_json(data, output)
        elif format == 'html':
            return self._generate_html(data, output)
        elif format == 'markdown':
            return self._generate_markdown(data, output)
        elif format == 'pdf':
            return self._generate_pdf(data, output)
        else:
            logger.error(f"Unknown format: {format}")
            return None
    
    def _gather_data(self) -> Dict:
        """Gather data from database"""
        from database import Database, Target, Subdomain, Port, Vulnerability, Scan, Technology, URL
        
        session = Database.get_session()
        try:
            # Get target
            target = session.query(Target).filter_by(domain=self.target).first()
            if not target:
                logger.warning(f"Target {self.target} not found in database")
                return {}
            
            # Get latest scan
            scan = session.query(Scan).filter_by(target_id=target.id).order_by(Scan.started_at.desc()).first()
            
            # Get vulnerabilities
            vulnerabilities = []
            if scan:
                vulns = session.query(Vulnerability).filter_by(scan_id=scan.id).all()
                vulnerabilities = [{
                    'title': v.title,
                    'severity': v.severity,
                    'description': v.description,
                    'url': v.url,
                    'tool': v.tool,
                    'status': v.status
                } for v in vulns]
            
            # Count severities
            severity_counts = {
                'critical': sum(1 for v in vulnerabilities if v['severity'] == 'critical'),
                'high': sum(1 for v in vulnerabilities if v['severity'] == 'high'),
                'medium': sum(1 for v in vulnerabilities if v['severity'] == 'medium'),
                'low': sum(1 for v in vulnerabilities if v['severity'] == 'low'),
                'info': sum(1 for v in vulnerabilities if v['severity'] == 'info'),
            }
            
            # Get recon data
            subdomains_count = session.query(Subdomain).filter_by(target_id=target.id).count()
            ports_count = session.query(Port).join(Subdomain).filter(Subdomain.target_id == target.id).count()
            techs_count = session.query(Technology).join(Subdomain).filter(Subdomain.target_id == target.id).count()
            urls_count = session.query(URL).join(Subdomain).filter(Subdomain.target_id == target.id).count()
            
            return {
                'target': self.target,
                'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'scan_date': scan.started_at.strftime('%Y-%m-%d %H:%M:%S') if scan else 'N/A',
                'total_findings': len(vulnerabilities),
                'severity_counts': severity_counts,
                'vulnerabilities': vulnerabilities,
                'recon': {
                    'subdomains': subdomains_count,
                    'ports': ports_count,
                    'technologies': techs_count,
                    'urls': urls_count
                }
            }
            
        finally:
            session.close()
    
    def _generate_json(self, data: Dict, output: str = None) -> str:
        """Generate JSON report"""
        if output is None:
            output = self.output_dir / f"{self.target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        with open(output, 'w') as f:
            json.dump(data, f, indent=2)
        
        logger.info(f"JSON report saved to {output}")
        return str(output)
    
    def _generate_html(self, data: Dict, output: str = None) -> str:
        """Generate HTML report"""
        if output is None:
            output = self.output_dir / f"{self.target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        template = Template(self.HTML_TEMPLATE)
        html = template.render(**data)
        
        with open(output, 'w') as f:
            f.write(html)
        
        logger.info(f"HTML report saved to {output}")
        return str(output)
    
    def _generate_markdown(self, data: Dict, output: str = None) -> str:
        """Generate Markdown report"""
        if output is None:
            output = self.output_dir / f"{self.target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        md = f"""# Bug Bounty Security Report

**Target:** {data['target']}  
**Generated:** {data['timestamp']}  
**Scan Date:** {data['scan_date']}

## Executive Summary

- **Total Findings:** {data['total_findings']}
- **Critical:** {data['severity_counts']['critical']}
- **High:** {data['severity_counts']['high']}
- **Medium:** {data['severity_counts']['medium']}
- **Low:** {data['severity_counts']['low']}
- **Info:** {data['severity_counts']['info']}

## Reconnaissance Results

- **Subdomains Found:** {data['recon']['subdomains']}
- **Open Ports:** {data['recon']['ports']}
- **Technologies Detected:** {data['recon']['technologies']}
- **URLs Discovered:** {data['recon']['urls']}

## Vulnerabilities

| Severity | Title | URL | Tool |
|----------|-------|-----|------|
"""
        for vuln in data['vulnerabilities']:
            md += f"| {vuln['severity'].upper()} | {vuln['title']} | {vuln['url']} | {vuln['tool']} |\n"
        
        md += "\n## Detailed Findings\n\n"
        for vuln in data['vulnerabilities']:
            md += f"""### {vuln['title']}

- **Severity:** {vuln['severity'].upper()}
- **URL:** {vuln['url']}
- **Description:** {vuln['description']}
- **Tool:** {vuln['tool']}

---

"""
        
        with open(output, 'w') as f:
            f.write(md)
        
        logger.info(f"Markdown report saved to {output}")
        return str(output)
    
    def _generate_pdf(self, data: Dict, output: str = None) -> str:
        """Generate PDF report (requires weasyprint)"""
        # First generate HTML
        html_output = self._generate_html(data, None)
        
        if output is None:
            output = self.output_dir / f"{self.target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        try:
            from weasyprint import HTML
            HTML(html_output).write_pdf(output)
            logger.info(f"PDF report saved to {output}")
            return str(output)
        except ImportError:
            logger.error("weasyprint not installed, cannot generate PDF")
            return html_output
